apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: mhouas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:4.4
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: "0.1"      
            memory: "300Mi"   
          limits:
            cpu: "0.2"       
            memory: "400Mi"   
  
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mhouas
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017       
    targetPort: 27017  
  type: ClusterIP
