apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
  namespace: mhouas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
      - name: webdb-container
        image: mah5000/site_web:2.0.0
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongodb://root:example@mongodb-service.mhouas.svc.cluster.local:27017/" # fully qualified domain name (FQDN) for KubeDNS
        - name: MONGO_DB_NAME
          value: "flask_app_db"
        - name: MONGO_COLLECTION_NAME
          value: "requests"     
        resources:
          requests:
            cpu: "0.1"
            memory: "100Mi"
          limits:
            cpu: "0.2"
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: webdb-service
  namespace: mhouas
spec:
  selector:
    app: webdb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP