apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnodb-deployment
  namespace: mhouas
  labels:
    app: webnodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webnodb
  template:
    metadata:
      labels:
        app: webnodb
    spec:
      containers:
      - name: webnodb-container
        image: mah5000/site_web:1.0.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "0.1"
            memory: "100Mi"
          limits:
            cpu: "0.2"
            memory: "200Mi"
