version: '2.32.1'

services:
  flask_no_db:
    build:
      context: ./flask_no_db
      dockerfile: Dockerfile
    container_name: flask_no_db
    ports:
      - "5001:5000"
    networks:
      - app_network

  flask_db:
    build:
      context: ./flask_db
      dockerfile: Dockerfile
    container_name: flask_db
    ports:
      - "5002:5000"
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:4.4
    container_name: mongodb_container
    ports:
      - "27017:27017"
    networks:
      - app_network

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_load_balancer
    ports:
      - "8080:80"
    depends_on:
      - flask_no_db
      - flask_db
    networks:
      - app_network

networks:
  app_network:
